// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7c64rxLk0hl_7tUnnPuznvbpJg-wLirM',
    appId: '1:59908804787:web:f62d3e68d02978485f20c6',
    messagingSenderId: '59908804787',
    projectId: 'little-minds-352e3',
    authDomain: 'little-minds-352e3.firebaseapp.com',
    storageBucket: 'little-minds-352e3.appspot.com',
    measurementId: 'G-F4NXH7PDEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZNwK7J65kuD0gLBsOINXHCQDRGuTNDiE',
    appId: '1:59908804787:android:e2c06aa8a5111b565f20c6',
    messagingSenderId: '59908804787',
    projectId: 'little-minds-352e3',
    storageBucket: 'little-minds-352e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrD984qgr0aYHgMB0IZ6S-REi38qPSIFk',
    appId: '1:59908804787:ios:352c8ceec7eea0265f20c6',
    messagingSenderId: '59908804787',
    projectId: 'little-minds-352e3',
    storageBucket: 'little-minds-352e3.appspot.com',
    iosBundleId: 'com.example.mindApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrD984qgr0aYHgMB0IZ6S-REi38qPSIFk',
    appId: '1:59908804787:ios:352c8ceec7eea0265f20c6',
    messagingSenderId: '59908804787',
    projectId: 'little-minds-352e3',
    storageBucket: 'little-minds-352e3.appspot.com',
    iosBundleId: 'com.example.mindApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7c64rxLk0hl_7tUnnPuznvbpJg-wLirM',
    appId: '1:59908804787:web:f1c230415f9db5bf5f20c6',
    messagingSenderId: '59908804787',
    projectId: 'little-minds-352e3',
    authDomain: 'little-minds-352e3.firebaseapp.com',
    storageBucket: 'little-minds-352e3.appspot.com',
    measurementId: 'G-HSMDWKHVDH',
  );
}
